### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by jonnoschmonno** [azarbayejani/bandcamp-tempo-adjust#13]
heya!

this extension is exactly what my friends and I have been looking for, but we have two suggestions that would make it absolutely perfect:
1. would it be possible to make the pitching up and pitching down while changing the tempo of a track optional? we'd rather keep the track in its original pitch while changing its tempo (for DJ-purposes).
2. would it be possible to have this exact same extension work for either Soundcloud, YouTube or Spotify as well? many of the tracks that we'd like to check in different tempos aren't available on Bandcamp.

would love to hear from you and thanks for the effort! :)

**Comment by azarbayejani** [comment]
Hi!

> 1. would it be possible to make the pitching up and pitching down while changing the tempo of a track optional? we'd rather keep the track in its original pitch while changing its tempo (for DJ-purposes).

I plan to do this at some point, but it will probably be a global setting (I don't want to muck up the Bandcamp UI with too many options)

> 2. would it be possible to have this exact same extension work for either Soundcloud, YouTube or Spotify as well? many of the tracks that we'd like to check in different tempos aren't available on Bandcamp.

At this time I only plan on working on this for Bandcamp. The way I grab the files to do beat detection is very specialized to Bandcamp. If you are looking for tools that allow you to adjust pitch on other websites (but not detect tempo), there are more generalized tools available like [Transpose](https://transpose.video)

**Comment by jonnoschmonno** [comment]
thanks a lot for your reply, looking forward to any future updates to this extension! also Transpose is a good one, didn't know about it yet.

**Comment by NedBM** [comment]
Hey been an active user of the extension for awhile and love it! I have been thinking about making quick extension for organizing the wishlists as mine grows. 

I see you mentioned not wanting to muck up the UI, was wondering if this is something you would have any interest in adding to this project. 

Quick Mock up of what I am talking about:
![Screenshot 2024-11-02 at 9 53 19 PM](https://github.com/user-attachments/assets/03a825d5-d6b8-47fa-8025-41332eed91e9)

All good if not! Thanks again for this sweet extension.

**Comment by azarbayejani** [comment]
@jonnoschmonno an option to keep the track's pitch the same is in the latest version as the "Master Tempo" button

**Comment by jonnoschmonno** [comment]
this is perfect, thanks a lot! :)
