### ISSUE TITLE
Add pitch slider to wishlist view

### ISSUE THREAD

**Issue by vzellweg** [azarbayejani/bandcamp-tempo-adjust#4]
The pitch slider is currently only implemented in the album or song view. It would be cool if it could work on the wishlist view, since the wishlist functions sort of like a playlist of songs.

Ideally, this feature would work with the continuous wishlist playback enabled by [this plugin](https://chrome.google.com/webstore/detail/bandcamp-streamer/hopclencgmfjiipjmlenfcdgcdblfmjh). So one could let their wishlist play continuously, and always be able to adjust the pitch of the currently playing track.

**Comment by azarbayejani** [comment]
I'll look into this!
