### ISSUE TITLE
Display actual BPM

### ISSUE THREAD

**Issue by assada** [azarbayejani/bandcamp-tempo-adjust#5]
Need to display actual BPM of tracks.

**Comment by assada** [comment]
Wow! just build master branch! Can you, please, publish latest master to chrome store?
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1472664/211580406-52d84e0b-5fc1-4274-8340-72ed5751aa6b.png">

**Comment by azarbayejani** [comment]
It is in the process of being published and waiting for approval.
